[package]
name = "plainchant"
version = "0.3.0"
authors = ["Jack Byrne <jack.byrne@durham.ac.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.2"
chrono = "0.4"
futures = "0.3.5"
bytes = "0.5.4"
rand = "0.7.3"
image = "0.23.8"
toml = "0.5.6"
lazy_static = "1.4.0"
regex = "1.5"
